services:

  mysql:
    image: mysql:8.4
    container_name: mysql_bd2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      mysql_network:
        ipv4_address: 10.1.100.2

networks:
  mysql_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.100.0/24